### ISSUE TITLE
Build fails with servant-0.5

### ISSUE THREAD

**Issue by aljce** [3noch/chess-finder-servant-demo#1]
kyle@Kyles-Laptop:~/Programming/haskell/chess-finder-servant-demo/front$ make
cd no-ghcjs \
    && export PATH=$(dirname $(stack exec which ghc)):$(dirname $(stack exec which happy)):$PATH \
    && cd - \
    && stack build
/home/kyle/Programming/haskell/chess-finder-servant-demo/front
Ignoring that the GHCJS boot package "aeson" has a different version, 0.9.0.1, than the resolver's wanted version, 0.8.0.2
Ignoring that the GHCJS boot package "attoparsec" has a different version, 0.13.0.1, than the resolver's wanted version, 0.12.1.6
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.3.3
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.0.2
Ignoring that the GHCJS boot package "vector" has a different version, 0.11.0.0, than the resolver's wanted version, 0.10.12.3
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.1.3
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.7.1.2
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.2.0
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.6.2
Ignoring that the GHCJS boot package "primitive" has a different version, 0.6.1.0, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.4.2.0
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:  
      servant-reflex: needed (-any), couldn't resolve its dependencies
    needed for package front-0.1

--  Failure when adding dependencies:  
      servant: needed (==0.5._), 0.6 found (latest applicable is 0.5)
    needed for package servant-reflex-0.1
Makefile:14: recipe for target 'build' failed
make: *_\* [build] Error 1

I was attempting to build this to solve: https://github.com/luigy/try-stack-reflex/issues/6

**Comment by 3noch** [comment]
Hahaha, terribly sorry. I am aware of this. I didn't expect anyone to actually try to build it! I do plan on fixing it eventually, but my apologies for the confusion.

**Comment by 3noch** [comment]
The problem is I need a patched version of that library which isn't released.

**Comment by aljce** [comment]
Haha well I will close this issue then!
